server:
  port: 8050
spring:
  application:
    name: wf-fpd-config-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leng0212/wf-fpd
          search-paths: config-repo
          username: leng0212@163.com
          password: leng1992
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/