server:
  port: 8001
spring:
  application:
    name: wf-fpd-provider-product    # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
    ddl-auto: none
  datasource:                           # 指定数据源
     profiles: test
     url: jdbc:mysql://localhost:3306/test 
     driver-class-name: com.mysql.jdbc.Driver  
     username: root  
     password: 123456  
     hikari:  
     maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上  
     maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)  
mybatis:  
  mapperLocations: classpath:mapper/*.xml  
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true