server:
  port: 8080
  
logging:
  level:
    debug
    
spring:
  rabbitmq: 
    addresses:  127.0.0.1:5672
    username: root
    password: 123456  
    publisherConfirms: true
    queueName: orderQueue
    keys:
      orderRouting: www.wanfin.com.bussiness.order.*
    exchange: orderExchange
    